### ISSUE TITLE
Soul of Bat couldn't be found in 1st Castle

### ISSUE THREAD

**Issue by bassvirtuoso** [sotnrando/sotnrando#1]
Soul of Bat couldn't be found in 1st Castle - this meant that I couldn't go into catacombs east area to get spikebreaker armor, which leads to silver ring - without silver ring, I can't get holy glasses and unlock the 2nd castle. I realize there's a speedrunning clip that can be done to get me into the holy glasses area under clock, but I'm a bit too casual to pull that off when playtesting this.

I was able to circumvent this bug by loading in the vanilla ISO (ripped from my PS1 disc) and grabbing Soul of Bat from the library location and saving, then reloading this rando seed back up and finishing the tasks needed to get 2nd castle unlocked.

I also noticed a few times where I'd grab a randomized relic and then another relic would suddenly appear in the same place. Sometimes the second relic would immediately appear and sometimes leaving the room and re-entering the room would make a second relic appear. This happened at the east side elevator where I had gotten the underwater relic and then a wolf relic appeared there again later when I came back to the area.

I don't know how to get the seed number, the site never gave me one and it's not built into the naming convention when you are prompted to save the file. I can attach the file here if need be, otherwise let me know how I can find the seed number.

**Comment by 3snowp7im** [comment]
Did you have soul of mist and power of mist? If you so, you are able to get spike breaker. There was a bug that allowed placing of bat relic in 2nd castle if you just had sonar assuming the player would be able to get spike breaker, but that should be fixed in latest release. The relic duping glitch should be fixed in clock tower and outer wall as well. Seed values will also be part of the file name when downloading in the latest release. Please create separate issues for each bug/feature/improvement in the future so it's easier to track progress. Going to close this issue, but please reopen new issues if anything persists.
