### ISSUE TITLE
Request - Statamizer

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [sotnrando/sotnrando#16]
I would like random stats 🗡

**Comment by 3snowp7im** [comment]
there is already a stat roll when starting a new game, so stast are already random to the extent  that the game's original developers felt they would be balanced. the only places to go from there is to make them truly random or implement my own arbitrary stat limits. statistically, the former option would result in overpowered stats most of the time. the latter option is just reinventing the wheel due to the fact that the vanilla game has its own sensible limits.

**Comment by P3rf3ctXZer0** [comment]
I was unaware the game was so rigid :(

**Comment by SenseiLeRoof** [comment]
I know I'm late to this party, but stats in vanilla are NOT random. They're directly based on your performance during the prologue or the use of the Luck Code if you used it.

**Comment by TalicZealot** [comment]
The point pool is determined by the prologue time, but the distribution is random.
