### ISSUE TITLE
Feature request: Option to randomize location of Gold Ring, Silver Ring, Spike Breaker, Holy Glasses

### ISSUE THREAD

**Issue by halgorithm** [sotnrando/sotnrando#24]
The Holy Glasses are always needed to reach the inverted castle, but getting them always requires the same routine of fetching the Spike Breaker and rings first from the same places. Because they are essentially key items that gate access to certain areas, I argue there should be an option to include these items in the relic locations pool and add item + relic dependency information for accessing their respective areas. This would add some more route variety to runs, e.g. if a player found the Holy Glasses early and immediately traveled to the inverted castle, as well as things like finding Soul of Bat there.

**Comment by 3snowp7im** [comment]
Having their locations randomized could often lead to very agonizing seeds, and would require another layer of item logic in order to implement safely. That is to say, every room would require it's own ability locks are satisfied before a progression item is placed there. An easier path might be to shuffle progression items among their own locations, however, there aren't many options that are safe while providing a unique experience.

**Comment by halgorithm** [comment]
To clarify, I didn't mean that these four items should be randomized into any item spot in any room of the castle (that would indeed be truly agonizing). Rather, they are essentially treated the same as the other relics and can appear instead of one at each relic location (e.g. find Spike Breaker on the Cube of Zoe's pedestal). Relics could also now be placed in these four item's rooms instead (e.g. defeat the Succubus to receive the Heart of Vlad).

**Comment by 3snowp7im** [comment]
Unfortunately, I don't think it's possible to swap items with relics and vice-versa :(

**Comment by halgorithm** [comment]
Damn, that's a shame.

**Comment by bjhanberry** [comment]
To piggyback off this - would it be possible to shuffle just the gold ring into a pool of non-essential boss rewards?(meaning the item room after the boss room, not replacing the HP up) Thinking this would provide some incentive to fight bosses that are always skipped in the randomizer (e.g. Scylla) due to them not having relic rewards.

I think requiring spike armor/vanilla silver ring location as set progression is solid but the succubus fight could be exchanged with any other and open up more of the castle to exploration/routing for more interesting overall runs.

Edit: realizing now there aren't very many options to implement this unless you make some separate "special item" pool for reward rooms which could be arbitrary to decide which rooms qualify.

**Comment by 3snowp7im** [comment]
I take back what I said previously about a logic table being a requirement for this feature. It could be implemented without such a table. Unfortunately, the reality is just as bleak in an uninteresting way. If progression items were randomized, you would often gets seeds that become an all out scavenger hunt requiring the player to search every corner of first castle for holy glasses (the only item you actually need to get to second castle). Rarely though, you might get holy glasses early, making the seed impressively boring. I don't think adding this feature would be that difficult, however, I'm not just interested in implementing it as I think it lacks any value add.

**Comment by 3snowp7im** [comment]
This is added in version 2.0.0
