### ISSUE TITLE
Feature request: Behavior attributes randomization

### ISSUE THREAD

**Issue by halgorithm** [sotnrando/sotnrando#25]
Dumping some ideas here, assuming any of these are potentially tweakable and not hardcoded/prohibitively difficult to randomize.

Weapons: attributes of behaviors like attack strength/duration/damage type, projectile speed/distance, etc.
Subweapons: heart cost, strength/speed/distance, etc.
Armor/accessories: defense value, base stat boosts, cape colors, other effects
Enemies: stats, resistances, movement/attack/projectile speed, AI constants?

**Comment by 3snowp7im** [comment]
Cape colors are randomized since 4c7459228cf7dec8c258aecfd9190f0fc5db8cd6

**Comment by 3snowp7im** [comment]
Weapon, item, and armor stats are now included in the stat randomizer feature of the 3.x releases. I do not intend to randomize enemy stats because that can drastically change the playability of seeds, possibly making seeds practically unbeatable for most players. I'm also not favoring the idea of randomizing subweapon attributes like heart cost or damage. I don't feel it adds anything to the game.
