### ISSUE TITLE
Not a relic soft lock, per-se, but you can get the Gold and Silver Rings before you get a chance to escape with this seed

### ISSUE THREAD

**Issue by pervidefedback** [sotnrando/sotnrando#41]
I used append seed to filename so I will give you the seed number on the file name.
1589571264837 - seed

**Comment by 3snowp7im** [comment]
You didn't fill out the issue template so I'm not able to provide much help since I have no idea what randomization settings or relic placement logic was used in this seed. The seed alone is useless. If you used the Safe preset, then on that seed, Silver Ring was at Rib of Vlad, which would have required you get some form of flight first. If this was an adventure seed, then Gold Ring was at Spike Breaker, which would have required Soul of Bat. If you didn't use a preset at all, you will have to provide the exact settings you used otherwise there is no way for anyone to generate the same result you got. Please use the issue template next time you submit a bug report.

**Comment by pervidefedback** [comment]
Alright so I need all the relevant info at the time of making the seed.  I don't have any of that.  There's no way I can go back from the filename and get that info?  If no then just close this.

**Comment by 3snowp7im** [comment]
From your seed I was able to determine the date it was generated as May 15. I checked out the randomizer version on that day and generated a Safe preset seed and it looks like the Holy Glasses location was empty, meaning it was not part of the placement logic. Because of this, the escape requirements were not considered, so it was possible to access that location without having a means of escaping. This should be fixed in the latest release https://github.com/3snowp7im/SotN-Randomizer/commit/359c1dfdc27be564b51c1885acef1a2fb93da086
