### ISSUE TITLE
Sotn Randomizer Freezes

### ISSUE THREAD

**Issue by buffyBot30** [sotnrando/sotnrando#5]
When going through the door from Royal Chapel into the previous area, the game freezes.  I have attached the save game data, using ESPXE PS1 emulator.  You can just load the game, and go right.  2nd file, named Rando.
Seed: 1554327833996

[Symphony of the Night.zip](https://github.com/3snowp7im/SotN-Relic-Randomizer/files/3041101/Symphony.of.the.Night.zip)

**Comment by 3snowp7im** [comment]
This is not a bug in the randomizer but actually the result of how the original game was coded. If you load up your vanilla rom and get the wolf relic, then candle kick in the clock room to get to olrox quarters (it's a trick used in the speedrun), you can go through that door connecting chapel to alchemy lab from the chapel side and the game will softlock. This is due to the cutscene with maria triggering while alucard is on the "wrong" side of the room. I'm not sure how fixable this is, but I can look into it.

**Comment by 3snowp7im** [comment]
The maria cutscenes that cause this softlock are disabled in https://github.com/3snowp7im/SotN-Relic-Randomizer/commit/7b7fcf797f04eeec8ccc3e54474e4eff14589c75
