### ISSUE TITLE
Feature Request: Compatibility with Tonyhax

### ISSUE THREAD

**Issue by ezgoodnight** [sotnrando/sotnrando#68]
After doing some searching, I am looking for your thoughts or corrections on this. After making a file, I used Alcohol and  it appears to have burned a SOTN disc with the randomized BIN.

I tried loading it with Tonyhax on my PS1 and it seems like it is missing boot information and other associated files the Playstation needs to load.

![PXL_20210614_220121566](https://user-images.githubusercontent.com/11281259/121965262-c1506200-cd3a-11eb-9a20-916e007e866b.jpg)

Looking at the Readme, it appears you list various softwares that will load images, so I'm _assuming_ the associated files are removed or made unusable and only work with various image loaders, as described.

Either that or I made my disc wrong, or missed some critical information.

Is it even _possible_ to make the Randomizer compatible with Tonyhax?

**Comment by johnoliverdriscoll** [comment]
I have never tried loading a randomized bin from a burned disc, but I have loaded a bin with PSIO on a PS1 and via USB on a PS2. Randomization does not mangle any boot information, otherwise those methods I have used would not work either. I assume you have already confirmed that you can run a burned disc of your vanilla bin?

**Comment by 3snowp7im** [comment]
I have never tried loading a randomized bin from a burned disc, but I have loaded a bin with PSIO on a PS1 and via USB on a PS2. Randomization does not mangle any boot information, otherwise those methods I have used would not work either. I assume you have already confirmed that you can run a burned disc of your vanilla bin?

**Comment by ezgoodnight** [comment]
Trying to recreate the issue, I have created another disc and this one runs like a dream with Tonyhax. I am not sure why the first one does what it does, I will try and make discs with a few new seeds and see if there is anything that I can learn. 

As it stands, it seems this software works with a burned disc and Tonyhax on my 5501.

**Comment by 3snowp7im** [comment]
I assume you burned your previous image incorrectly, or some error occurred during the disc burning. If you find that there are reproducible steps that you can use which cause the randomizer to destroy the boot information, please create a new ticket with that information.
